GET http://localhost:3000/


### Register ---------------------------------
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "fullname": "Hermione Granger",
  "email": "hermionegranger3@email.com",
  "password": "secret123",
  "passwordConfirm": "secret123"
}


### Login ---------------------------------
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "hermionegranger@email.com",
  "password": "secret123"
}


### Groups ---------------------------------
GET http://localhost:3000/api/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzY2NzgxNCwiZXhwIjoxNjUzNjcxNDE0fQ.8cJ1Vo5SfGPSqehD_AUyu_iVbWvN8lhxTfQ_J9ObK-I
