###
GET http://localhost:3000/

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "fullname": "Hermione Granger",
  "email": "hermionegranger@email.com",
  "password": "secret123"
}
###