GET http://localhost:3000/


### Register ---------------------------------
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "fullname": "Hermione Granger",
  "email": "hermionegranger3@email.com",
  "password": "secret123",
  "passwordConfirm": "secret123"
}


### Login ---------------------------------
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "hermionegranger@email.com",
  "password": "secret123"
}

### Groups ---------------------------------
GET http://localhost:3000/api/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzgxNDM3MCwiZXhwIjoxNjUzODE3OTcwfQ.9IFAxM7jn9E1aViENlBG-EMPxaf1T04Lu_-f0QrVOus

###
POST http://localhost:3000/api/groups
Content-Type: application/json

{
  "name": "Polar Night in Norway"
}

### Accounts -------------------------------
GET http://localhost:3000/api/accounts


### Bills ----------------------------------
GET http://localhost:3000/api/bills
